In [4]:
from scipy.fft import fft, ifft
import numpy as np
from scipy.linalg import dft
from sympy import ntt, intt

np.set_printoptions(precision=2, suppress=True)

In [2]:
def list_to_int(l):
    return int(''.join(list(map(lambda x: str(x),list(l)[::-1]))))

def coef_l_to_int(l, base=10):
    N = len(l)
    sum_i = 0
    for i in range(N):
        sum_i += l[i]*(base**i)
    return sum_i

In [81]:
N = 2

a = np.random.randint(1,9, size=N)
b = np.random.randint(1,9, size=N)

a_vec = list(np.concatenate([a,np.random.randint(1, size=N)]))
b_vec = list(np.concatenate([b,np.random.randint(1, size=N)]))

a_int = list_to_int(a)
b_int = list_to_int(b)

In [82]:
a, a_vec, a_int

(array([3, 6]), [3, 6, 0, 0], 63)

In [83]:
b, b_vec, b_int

(array([3, 7]), [3, 7, 0, 0], 73)

In [84]:
a_int*b_int

4599

# FFT

## Ejemplo 1

In [7]:
f_a = fft(np.array([2, 8, 0, 0]))
f_a

array([10.-0.j,  2.-8.j, -6.-0.j,  2.+8.j])

In [8]:
f_b = fft(np.array([4, 3, 0, 0]))
f_b

array([7.-0.j, 4.-3.j, 1.-0.j, 4.+3.j])

In [9]:
f_c = np.multiply(f_a,f_b)
f_c

array([ 70. -0.j, -16.-38.j,  -6. +0.j, -16.+38.j])

In [10]:
ifft(f_c).real

array([ 8., 38., 24.,  0.])

In [11]:
coef_l_to_int(ifft(f_c).real.astype(int))

2788

## Ejemplo 2

In [85]:
f_a = fft(a_vec)

In [86]:
f_b = fft(b_vec)

In [87]:
f_c = np.multiply(f_a,f_b)

In [88]:
ifft(f_c).real.astype(int)

array([ 9, 39, 42,  0])

In [89]:
coef_l_to_int(ifft(f_c).real.astype(int))

4599

# NTT

## Ejemplo 1

In [17]:
f_a = ntt(np.array([2,8,0,0]), prime=262657)
f_a

[10, 156751, 262651, 105910]

In [18]:
f_b = ntt(np.array([4,3,0,0]), prime=262657)
f_b

[7, 91617, 1, 171048]

In [19]:
f_c = np.multiply(f_a,f_b)
f_c

array([         70, 14361056367,      262651, 18115693680])

In [20]:
intt(f_c, prime=262657)

[8, 38, 24, 0]

## Ejemplo 2

In [3]:
f_a = ntt([1,0], prime=262657)

NameError: name 'ntt' is not defined

In [137]:
f_b = ntt([5,0], prime=262657)

In [138]:
f_a,f_b

([3, 3], [5, 5])

In [139]:
f_c = np.multiply(f_a,f_b)

In [140]:
f_c

array([15, 15])

In [141]:
intt(f_c, prime=262657)

[15, 0]

In [142]:
ntt(np.array([5,1]), prime=262657)

[6, 4]

In [144]:
ntt(np.array([15,0]), prime=262657)

[15, 15]

In [5]:
intt(np.array([1,0]), prime=262657)

[131329, 131329]

In [6]:
intt(np.array([0,1]), prime=262657)

[131329, 131328]

In [9]:
(pow(2,-1,262657) * 5) % 262657

131331

In [10]:
primitive_root(262657)

5

In [143]:
coef_l_to_int(intt(f_c, prime=262657))

15

In [99]:
np.dot(np.array([[1,1,1,1],
          [1,5,25,125],
          [1,25,625,15625],
          [1,125,15625,114526]]),
       np.array([3,7,0,0]))

array([ 10,  38, 178, 878])

In [98]:
np.mod(np.array([    27,    679,  65859, 537363]),262657)

array([   27,   679, 65859, 12049])

In [68]:
(ntt(f_c, prime=262657) /f_b).astype(int)

array([     8, 261057, 209705, 221998,      0, 237786,  52956,  67142])

In [ ]:
coef_l_to_int(intt(f_c, prime=262657))

In [ ]:
a_hat = ntt(np.array([2, 0, 0, 0]), prime=5)

In [ ]:
b_hat = ntt(np.array([3,0, 0, 0 ]), prime=5)

In [ ]:
b_hat

In [ ]:
c_hat = np.multiply(a_hat, b_hat)
c_hat

In [ ]:
intt(np.array([1,1]), prime=5)

In [ ]:
d_hat = ntt(np.array([4,0, 0, 0 ]), prime=5)

In [ ]:
np.mod(np.multiply(a_hat, d_hat),5)

In [ ]:
intt(np.mod(np.multiply(a_hat, d_hat),5), prime=5)

In [ ]:
np.multiply(a_hat, d_hat)

In [ ]:
N = 256
a = list(np.concatenate([np.random.randint(9, size=N),np.random.randint(1, size=N)]))

In [ ]:
#ntt(a, prime=262657)

In [ ]:
ntt(np.array([8,0,0,0]), prime=262657)

In [ ]:
f_a = ntt(np.array([0,0,2000,0,0,0,0,0]), prime=262657)
f_a

In [ ]:
f_b = ntt(np.array([0,0,2000,0,0,0,0,0]), prime=262657)
f_b

In [ ]:
f_c = np.multiply(f_a,f_b)
f_c

In [ ]:
intt(f_c, prime=262657)

In [ ]:
np.mod(np.dot(np.array([[1,1,1,1],
                  [1,2,4,8],
                  [1,4,16,64],
                  [1,8,64,512]]),np.array([1, 4, 0, 0])),5)

In [ ]:
ntt(np.array([1, 4, 0, 0]), prime=5)

In [ ]:
np.dot(np.array([[1,1],
                 [1,2]]),np.array([1,4]))

In [ ]:
from sympy.ntheory import totient, factorint

In [ ]:
totient(262657)

In [1]:
from sympy.ntheory.residue_ntheory import primitive_root

In [2]:
primitive_root(9)

2

In [154]:
primitive_root(5)

2

In [95]:
primitive_root(262657)

5

In [ ]:
from sympy.ntheory import primefactors

In [ ]:
sorted(factorint(262656).items())

In [ ]:
# Python3 program to find primitive root
# of a given number n
from math import sqrt
 
# Returns True if n is prime
def isPrime( n):
 
    # Corner cases
    if (n <= 1):
        return False
    if (n <= 3):
        return True
 
    # This is checked so that we can skip
    # middle five numbers in below loop
    if (n % 2 == 0 or n % 3 == 0):
        return False
    i = 5
    while(i * i <= n):
        if (n % i == 0 or n % (i + 2) == 0) :
            return False
        i = i + 6
 
    return True
 
""" Iterative Function to calculate (x^n)%p
    in O(logy) */"""
def power( x, y, p):
 
    res = 1 # Initialize result
 
    x = x % p # Update x if it is more
              # than or equal to p
 
    while (y > 0):
 
        # If y is odd, multiply x with result
        if (y & 1):
            res = (res * x) % p
 
        # y must be even now
        y = y >> 1 # y = y/2
        x = (x * x) % p
 
    return res
 
# Utility function to store prime
# factors of a number
def findPrimefactors(s, n) :
 
    # Print the number of 2s that divide n
    while (n % 2 == 0) :
        s.add(2)
        n = n // 2
 
    # n must be odd at this point. So we can 
    # skip one element (Note i = i +2)
    for i in range(3, int(sqrt(n)), 2):
         
        # While i divides n, print i and divide n
        while (n % i == 0) :
 
            s.add(i)
            n = n // i
         
    # This condition is to handle the case
    # when n is a prime number greater than 2
    if (n > 2) :
        s.add(n)
 
# Function to find smallest primitive
# root of n
def findPrimitive( n) :
    s = set()
 
    # Check if n is prime or not
    if (isPrime(n) == False):
        return -1
 
    # Find value of Euler Totient function
    # of n. Since n is a prime number, the
    # value of Euler Totient function is n-1
    # as there are n-1 relatively prime numbers.
    phi = n - 1
 
    # Find prime factors of phi and store in a set
    findPrimefactors(s, phi)
 
    # Check for every number from 2 to phi
    for r in range(2, phi + 1):
 
        # Iterate through all prime factors of phi.
        # and check if we found a power with value 1
        flag = False
        for it in s:
 
            # Check if r^((phi)/primefactors)
            # mod n is 1 or not
            if (power(r, phi // it, n) == 1):
 
                flag = True
                break
             
        # If there was no power with value 1.
        if (flag == False):
            return r
 
    # If no primitive root found
    return -1

In [ ]:
# Driver Code
n = 262657
print("Smallest primitive root of",
         n, "is", findPrimitive(n))
 
# This code is contributed by
# Shubham Singh(SHUBHAMSINGH10)

In [ ]:
T_n = lambda n: 16**n + 8**n + 4**n + 2**n + 1

In [ ]:
T_n(25)

In [ ]:
from sympy import isprime

In [ ]:
isprime(262657)

In [158]:
len([1,4,0,0]).bit_length()-1

2

In [163]:
if 262657&(262657-1):
    print(1)

1


In [161]:
1&10

0